context("non-defaults")
test_that("widgets create listbuilder objects (non-default)", {
    expect_is(attended_event(1970, 3052), "listbuilder")
    expect_is(class_campaign_year(1990:2000), "listbuilder")
    expect_is(gave_to_area(business, chemistry, CALP), "listbuilder")
    expect_is(has_affiliation(MB1), "listbuilder")
    expect_is(has_capacity(1:4, 7), "listbuilder")
    expect_is(has_degree_from(business, LS), "listbuilder")
    expect_is(has_implied_capacity(more, MOST, somewhat_likely), "listbuilder")
    expect_is(has_interest(INT, GPS), "listbuilder")
    expect_is(has_major_gift_score(some, least), "listbuilder")
    expect_is(has_philanthropic_affinity(GRK, GGHH), "listbuilder")
    expect_is(in_unit_portfolio(LS), "listbuilder")
    expect_is(lives_in_county(CA001), "listbuilder")
    expect_is(lives_in_msa(93730), "listbuilder")
    expect_is(lives_in_zip(94720, 70770), "listbuilder")
    expect_is(on_committee(BUS, ART), "listbuilder")
    expect_is(participated_in(ABC, DEF), "listbuilder")
    expect_is(played_sport(SOC), "listbuilder")
    expect_is(received_award(AWARD), "listbuilder")
    expect_is(works_in_county(CA001), "listbuilder")
    expect_is(works_in_msa(93730, 999338), "listbuilder")
    expect_is(works_in_zip("00730", 99999), "listbuilder")
})
