interest_code_synonyms <- function() {
    c(
        "libraries" = "LIB",
        "science" = "SCE",
        "architecture" = "ARH",
        "arts" = "ART",
        "family" = "FAM",
        "mathematics" = "MAT",
        "civic_affairs" = "CIV",
        "fashion_textiles" = "FAS",
        "volunteer_service" = "VSR",
        "education" = "EDU",
        "endowments_scholarships" = "ESC",
        "food" = "FOD",
        "health" = "HEA",
        "hobbies" = "HOB",
        "religion" = "REL",
        "wine" = "WIN",
        "athletics" = "ATH",
        "diversity_equity_inclusion" = "DEI",
        "philosophy" = "PHI",
        "psychology" = "PSY",
        "telecommunications" = "TEL",
        "animal_causes" = "ANI",
        "diverse_constituencies" = "DIV",
        "gaming" = "GAM",
        "history" = "HIS",
        "journalism" = "JOU",
        "literature" = "LIT",
        "transportation" = "TRA",
        "writing" = "WRI",
        "business" = "BUS",
        "entertainment" = "ENT",
        "international_affairs" = "INT",
        "economics" = "ECO",
        "environment" = "ENV",
        "endowments_fellowships" = "ESF",
        "museums" = "MUE",
        "stem" = "STE",
        "technology" = "TEC"
    )
}
