record_type_code_synonyms <- function() {
    c(
        "fdn_private" = "FP",
        "ucbf_trustee" = "TR",
        "corporation" = "CP",
        "fdn_corporate" = "FC",
        "ucbf_foundation" = "FU",
        "attendee_grad" = "GA",
        "ucb_guardian" = "GU",
        "current_student" = "ST",
        "alum_undergrad" = "AU",
        "ucb_parent_past" = "PX",
        "former_staff" = "SX",
        "automated_process" = "ZA",
        "faculty" = "FA",
        "faculty_emeritus" = "FE",
        "ucb_parent_current" = "PA",
        "former_ucbf_trustee" = "TX",
        "government_organization" = "GV",
        "trust_for_non_alumnus" = "TN",
        "attendee_undergrad" = "UA",
        "alum_grad" = "AG",
        "donor_advised_fund" = "DA",
        "foundation" = "FN",
        "other_organization" = "OO",
        "uc_regent" = "RG",
        "religious_organization" = "RO",
        "trust_for_alumnus" = "TA",
        "charitable_trust" = "TC",
        "founded_by_alumnus" = "AF",
        "non_ucb_educ_instit_assoc" = "ED",
        "friend_non_alum" = "IN",
        "former_uc_regent" = "RX",
        "staff" = "SF",
        "spouse" = "SP",
        "campus_related_org" = "CO",
        "former_faculty" = "FX"
    )
}
